# Generated by Django 2.2 on 2020-11-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maze_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ager',
            field=models.IntegerField(null=True),
        ),
    ]
